export { default as About } from './About';
export { default as Bingo } from './Bingo';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Home } from './Home';
export { default as LoggedIn } from './LoggedIn';
export { default as Privacy } from './Privacy';
export { default as Score } from './Score';
